// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package main

import (
	"fmt"
	"strings"
)

const (
	// LanguageUnset is a Language of type Unset.
	LanguageUnset Language = iota
	// LanguageGolang is a Language of type Golang.
	LanguageGolang
	// LanguageRust is a Language of type Rust.
	LanguageRust
)

var ErrInvalidLanguage = fmt.Errorf("not a valid Language, try [%s]", strings.Join(_LanguageNames, ", "))

const _LanguageName = "UnsetGolangRust"

var _LanguageNames = []string{
	_LanguageName[0:5],
	_LanguageName[5:11],
	_LanguageName[11:15],
}

// LanguageNames returns a list of possible string values of Language.
func LanguageNames() []string {
	tmp := make([]string, len(_LanguageNames))
	copy(tmp, _LanguageNames)
	return tmp
}

var _LanguageMap = map[Language]string{
	LanguageUnset:  _LanguageName[0:5],
	LanguageGolang: _LanguageName[5:11],
	LanguageRust:   _LanguageName[11:15],
}

// String implements the Stringer interface.
func (x Language) String() string {
	if str, ok := _LanguageMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Language(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Language) IsValid() bool {
	_, ok := _LanguageMap[x]
	return ok
}

var _LanguageValue = map[string]Language{
	_LanguageName[0:5]:                    LanguageUnset,
	strings.ToLower(_LanguageName[0:5]):   LanguageUnset,
	_LanguageName[5:11]:                   LanguageGolang,
	strings.ToLower(_LanguageName[5:11]):  LanguageGolang,
	_LanguageName[11:15]:                  LanguageRust,
	strings.ToLower(_LanguageName[11:15]): LanguageRust,
}

// ParseLanguage attempts to convert a string to a Language.
func ParseLanguage(name string) (Language, error) {
	if x, ok := _LanguageValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LanguageValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Language(0), fmt.Errorf("%s is %w", name, ErrInvalidLanguage)
}

// MarshalText implements the text marshaller method.
func (x Language) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Language) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLanguage(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
