name: Extract Changelog

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  extract-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Extract changelog section
      id: changelog
      run: |
        set -e

        #curl -L https://github.com/streamingfast/sfreleaser/releases/download/v0.12.0/sfreleaser_linux_x86_64.tar.gz | tar -xz
        #chmod +x sfreleaser
        sfreleaser="go run github.com/streamingfast/sfreleaser/cmd/sfreleaser@c2d4926ffcaf9a405ecf54cc476633944a573a92"

        $sfreleaser changelog extract-section --github-output="$GITHUB_OUTPUT" github://token:${{ github.token }}@${{ github.repository }}/$GITHUB_SHA/CHANGELOG.md

        echo "Changelog section extracted successfully"

    - name: Test changelog output
      run: |
        echo "=== Extracted Changelog Content ==="
        echo "${{ steps.changelog.outputs.changelog }}"
        echo "=== End of Changelog Content ==="