name: Extract Changelog

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  extract-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Extract changelog section
      id: changelog
      run: |
        set -e

        # Install sfreleaser using go install
        echo "Installing sfreleaser..."
        go install github.com/streamingfast/sfreleaser/cmd/sfreleaser@master

        echo "Extracting changelog section from GitHub..."
        changelog_content=$(sfreleaser changelog extract-section github://token:${{ github.token }}@${{ github.repository }}/$GITHUB_SHA/CHANGELOG.md)

        # Properly escape the content for GitHub Actions output
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        {
          echo "changelog<<$EOF"
          echo "$changelog_content"
          echo "$EOF"
        } >> "$GITHUB_OUTPUT"

        echo "Changelog section extracted successfully"

    - name: Test changelog output
      run: |
        echo "=== Extracted Changelog Content ==="
        echo "${{ steps.changelog.outputs.changelog }}"
        echo "=== End of Changelog Content ==="