name: Extract Changelog

on:
  # Only dispatch for show case purposes
  workflow_dispatch:

jobs:
  extract-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Extract changelog section
      id: changelog
      run: |
        curl -L https://github.com/streamingfast/sfreleaser/releases/download/v0.12.1/sfreleaser_linux_x86_64.tar.gz | tar -xz
        chmod +x sfreleaser

        ./sfreleaser changelog extract-section \
          github://token:${{ github.token }}@${{ github.repository }}/$GITHUB_SHA/CHANGELOG.md \
          --github-output="changelog:$GITHUB_OUTPUT"

    - name: Test changelog output
      run: |
        echo "=== Extracted Changelog Content ==="
        echo "${{ steps.changelog.outputs.changelog }}"
        echo "=== End of Changelog Content ==="